import type { ItemsConfig } from './types';

// 万一 items.json 请求失败时的兜底
export const DEFAULT_CONFIG: ItemsConfig = {
  rows: 5,
  cols: 4,
  wheelSpins: 3,
  tiers: ['特等奖', '一等奖', '二等奖', '三等奖', '幸运奖', '安慰奖', '谢谢参与'],
  items: [
    { id: 1, title: '三套定制键帽', tier: '特等奖', icon: 'Keyboard', iconColor: 'text-blue-600', value: '¥888', type: 'real' },
    { id: 2, title: '洗碗券一次', tier: '幸运奖', icon: 'Utensils', iconColor: 'text-green-600', value: '¥10', type: 'funny' },
    { id: 3, title: '一束浪漫鲜花', tier: '一等奖', icon: 'Flower', iconColor: 'text-pink-600', value: '¥520', type: 'real' },
    { id: 4, title: '不准生气券', tier: '幸运奖', icon: 'Ghost', iconColor: 'text-purple-600', value: '¥99', type: 'funny' },
    { id: 5, title: '一份真刮刮乐', tier: '二等奖', icon: 'Trophy', iconColor: 'text-yellow-600', value: '¥100', type: 'real' },
    { id: 6, title: '亲亲一个', tier: '幸运奖', icon: 'Smile', iconColor: 'text-red-500', value: '¥1314', type: 'funny' },
    { id: 7, title: '再来一瓶空气', tier: '幸运奖', icon: 'Zap', iconColor: 'text-cyan-500', value: '¥0', type: 'funny' },
    { id: 8, title: '陪逛街不喊累', tier: '幸运奖', icon: 'Star', iconColor: 'text-orange-500', value: '¥200', type: 'funny' },
    { id: 9, title: '清空购物车', tier: '幸运奖', icon: 'ShoppingCart', iconColor: 'text-amber-700', value: '¥100', type: 'funny' },
    { id: 10, title: '捏脚10分钟', tier: '幸运奖', icon: 'Coins', iconColor: 'text-yellow-700', value: '¥50', type: 'funny' },
    { id: 11, title: '奶茶一杯', tier: '三等奖', icon: 'Coffee', iconColor: 'text-amber-800', value: '¥25', type: 'real' },
    { id: 12, title: '电影票两张', tier: '三等奖', icon: 'Ticket', iconColor: 'text-red-600', value: '¥120', type: 'real' },
    { id: 13, title: '承包一周早餐', tier: '幸运奖', icon: 'Sun', iconColor: 'text-orange-400', value: '¥150', type: 'funny' },
    { id: 14, title: '最美称号', tier: '幸运奖', icon: 'Heart', iconColor: 'text-pink-400', value: '¥∞', type: 'funny' },
    { id: 15, title: '听我唠叨一次', tier: '幸运奖', icon: 'Music', iconColor: 'text-indigo-500', value: '¥200', type: 'funny' },
    { id: 16, title: '美美合照一张', tier: '三等奖', icon: 'Camera', iconColor: 'text-teal-500', value: '¥88', type: 'real' },
    { id: 17, title: '睡前故事一则', tier: '幸运奖', icon: 'Moon', iconColor: 'text-violet-500', value: '¥30', type: 'funny' },
    { id: 18, title: '承包家务一天', tier: '幸运奖', icon: 'Cloud', iconColor: 'text-sky-500', value: '¥200', type: 'funny' },
    { id: 19, title: '谢谢参与', tier: '谢谢参与', icon: 'Gift', iconColor: 'text-gray-400', value: '¥0', type: 'filler' },
    { id: 20, title: '谢谢参与', tier: '谢谢参与', icon: 'Star', iconColor: 'text-gray-400', value: '¥0', type: 'filler' },
  ],
  toasts: {
    real: [
      '男朋友的钱包在哭泣 😭',
      '哇塞！血赚不亏！',
      '这运气去买彩票吧！',
      '今晚加鸡腿！🍗',
      '男朋友要吃土了…',
      '暴富！暴富！暴富！',
      '男朋友的钱包已阵亡 💀',
      '恭喜！请立即截图保存证据',
    ],
    funny: [
      '哈哈哈这也算奖？',
      '恭喜获得空气一瓶 🌬️',
      '男朋友的诚意：★☆☆☆☆',
      '这个券建议立刻使用',
      '薅到了！薅到了！',
      '不准嫌弃！说好的不拒收！',
      '虽然不值钱但诚意满满（？）',
      '使用时请面带微笑',
    ],
    filler: [
      '哈哈哈哈非洲人实锤 🌍',
      '抱抱男朋友消消气',
      '命运：就不给你好的',
      '谢谢参与 = 谢谢惠顾本店',
      '这个位置风水不好…',
      '别灰心，还有机会！（大概）',
      '命运在嘲笑你 😏',
      '安慰奖都没有，惨…',
    ],
  },
};
